apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-service-frontend-sm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: web-f 
  endpoints:
  - targetPort: 3000
